name: GitHub Metrics

on:
  schedule:
    - cron: "17 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  metrics-left:
    runs-on: ubuntu-latest

    steps:
      - name: Generate left metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Vantalim12
          filename: metrics_left.svg

          template: classic
          config_timezone: Asia/Manila
          config_padding: 0, 8 + 11%

          # Profile / activity / repositories
          base: header, activity, community, repositories, metadata
          base_indepth: yes

          # Languages
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: percentage
          plugin_languages_limit: 8

          # Coding stats
          plugin_lines: yes

  metrics-right:
    runs-on: ubuntu-latest

    steps:
      - name: Generate right metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Vantalim12
          filename: metrics_right.svg

          template: classic
          config_timezone: Asia/Manila
          config_padding: 0, 8 + 11%

          # Disable normal profile blocks
          base: ""

          # Contribution calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # Recently starred repositories
          plugin_stars: yes
          plugin_stars_limit: 4

          # Issues / PR activity
          plugin_followup: yes
          plugin_followup_indepth: yes
